# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:
  call-workflow:
    uses: dheredia-ok/TestRepo1/.github/workflows/maven.yml@main
  
